version: 1

models:
  - SNACKS_Detalj_Bolter.ifc
  - SNACKS_Detalj_Jodringsbolt.ifc
  - SNACKS_Detalj_Lager.ifc
  - SNACKS_Detalj_Nivelleringsbolt.ifc
  - SNACKS_Detalj_Overgangsplate.ifc
  - SNACKS_Detalj_Pel.ifc
  - SNACKS_Detalj_Sluk.ifc
  - SNACKS_Detalj_Tilslutning_Kantbjelke.ifc

selection:
  ifc_class: IfcElement
  exclude_name_patterns:
    - '^Ramme$'

base_property_sets:
  - BIM_Tverrfaglig
  - KON_Felles

rules:
  - id: loose-materials
    name_pattern: '^Løsmasser_[12]$'
    property_sets:
      - KON_Løsmasser
    exclude_property_sets:
      - KON_Felles

  - id: reinforcement
    name_pattern: '^Armering_Rustfritt$'
    property_sets:
      - KON_Armering

  - id: landkar
    name_pattern: '^Landkar$'
    property_sets:
      - KON_Betong
    values:
      KON_Felles:
        'KON.10 - Konstruksjonsinndeling': Underbygning
        'KON.11 - Konstruksjonsdel': Landkar
        'KON.13 - Elementnavn': Landkar

  - id: transition-slab
    name_pattern: '^Overgangsplate$'
    property_sets:
      - KON_Betong
    values:
      KON_Felles:
        'KON.10 - Konstruksjonsinndeling': Underbygning
        'KON.11 - Konstruksjonsdel': Landkar
        'KON.13 - Elementnavn': Overgangsplate
