version: 1.0

models:
  - SNACKS_Detalj_Lager.ifc

spatial_structure:
  IfcProject: SNACKS Detalj Lager
  IfcSite: SNACKS Detalj Lager
  IfcBuilding: Bru
  IfcBuildingStorey: Lager

selection:
  ifc_class: IfcElement
  exclude_name_patterns:
    - '^Ramme$'
    - '^Midlertidig_stålrør$'

base_property_sets:
  - BIM_Tverrfaglig
  - KON_Felles

default_values:
  BIM_Tverrfaglig:
    'BIM.04 - MMI': '350'
    'BIM.05 - Elementnavn': Detaljelement
    'BIM.06 - Fag': KON
    'BIM.07 - Revisjon': A
    'BIM.08 - Revisjonsdato': '2023-01-16'

  KON_Felles:
    'KON.01 - Konstruksjonsnummer': K100
    'KON.03 - Akse': '01'
    'KON.10 - Konstruksjonsinndeling': Bru
    'KON.11 - Konstruksjonsdel': Lagerdetalj
    'KON.13 - Elementnavn': Detaljelement
    'KON.20 - Produksjonsenhet': PLD-1002
    'KON.30 - Plasseringsprioritet': 2 - Viker for 1
    'KON.31 - Plasseringsmerknad': Ikke angitt
    'KON.40 - Materialtype': Uspesifisert
    'KON.41 - Materialspesifikasjon': Uspesifisert
    'KON.51 - Produksjonsmerknad 1': Ikke angitt
    'KON.53 - Utførelsesmerknad 1': Ikke angitt

  KON_Betong:
    'BET.01 - Utførelsesklasse': '2'
    'BET.02 - Nøyaktighetsklasse': B
    'BET.04 - Materialspesifikasjon (dup)': B45 SV-Standard
    'BET.10 - Produksjonsmetode': Plasstøpt
    'BET.11 - Forskaling': Stående bord
    'BET.21 - Overdekning hovedarmering': 'UK, NS og FS: 75mm ±15mm, OK: 65mm ±15mm'
    'BET.30 - Diameter monteringsstenger': 12 mm
    'BET.31 - Overdekning monteringsstenger': 'UK, NS og FS: 60mm ±5mm, OK: 50mm ±5mm'

  KON_Lager:
    'LGR.01 - Lager-ID': LGR-001
    'LGR.02 - Type': Ikke angitt
    'LGR.03 - Funksjon': Brolager
    'LGR.10 - Bevegelse primærretning lager': Ikke angitt
    'LGR.11 - Bevegelse sekundærretning lager': Ikke angitt
    'LGR.12 - Tippvinkel [%]': 0
    'LGR.13 - Monteringsvinkel  [%]': 0
    'LGR.14 - Forinnstilling': Ikke angitt
    'LGR.20 - ULS Vertikallast, Vmax [kN]': 0
    'LGR.21 - ULS Horisontallast, Hmax1 [kN]': 0
    'LGR.22 - ULS Vertikallast for maksimal horisontallast, Vtilh1 [kN]': 0
    'LGR.23 - ULS Verikallast, Vmin2 [kN]': 0
    'LGR.24 - ULS Horisontallast for minimal vertikallast, Htilh2 [kN]': 0
    'LGR.50 - Jekkelast uten trafikklast [kN]': 0
    'LGR.51 - Jekkelast med trafikklast [kN]': 0
    'LGR.52 - Maksimal oppjekking': 0 mm

rules:
  - id: foundation
    name_pattern: '^Fundament$'
    property_sets:
      - KON_Betong
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Fundament
      KON_Felles:
        'KON.10 - Konstruksjonsinndeling': Underbygning
        'KON.11 - Konstruksjonsdel': Fundament
        'KON.13 - Elementnavn': Fundament
        'KON.40 - Materialtype': Betong
        'KON.41 - Materialspesifikasjon': B45 SV-Standard

  - id: landkar
    name_pattern: '^Landkar$'
    property_sets:
      - KON_Betong
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Landkar
      KON_Felles:
        'KON.10 - Konstruksjonsinndeling': Underbygning
        'KON.11 - Konstruksjonsdel': Landkar
        'KON.13 - Elementnavn': Landkar
        'KON.40 - Materialtype': Betong
        'KON.41 - Materialspesifikasjon': B45 SV-Standard

  - id: bearing-mortar
    name_pattern: '^Mørtel$'
    property_sets:
      - KON_Felles
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Mørtel
      KON_Felles:
        'KON.11 - Konstruksjonsdel': Lagerunderstøp
        'KON.13 - Elementnavn': Mørtel
        'KON.40 - Materialtype': Mørtel
        'KON.41 - Materialspesifikasjon': Ikke angitt

  - id: bearing
    name_pattern: '^Lager$'
    property_sets:
      - KON_Lager
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Lager
      KON_Felles:
        'KON.11 - Konstruksjonsdel': Lager
        'KON.13 - Elementnavn': Lager
        'KON.40 - Materialtype': Stål/gummi
        'KON.41 - Materialspesifikasjon': Ikke angitt
      KON_Lager:
        'LGR.01 - Lager-ID': Lager
