version: 1.0

models:
  - SNACKS_Detalj_Pel.ifc

spatial_structure:
  IfcProject: SNACKS Detalj Pel
  IfcSite: SNACKS Detalj Pel
  IfcBuilding: Bru
  IfcBuildingStorey: Pel

selection:
  ifc_class: IfcElement
  exclude_name_patterns:
    - '^Ramme$'

delete_property_sets:
  - Tekla Common
  - Tekla Quantity
  - SlabBaseQuantities
  - Pset_SlabCommon

base_property_sets:
  - BIM_Tverrfaglig
  - KON_Felles

default_values:
  BIM_Tverrfaglig:
    'BIM.04 - MMI': '350'
    'BIM.05 - Elementnavn': Detaljelement
    'BIM.06 - Fag': KON
    'BIM.07 - Revisjon': A
    'BIM.08 - Revisjonsdato': '2023-01-16'

  KON_Felles:
    'KON.01 - Konstruksjonsnummer': K100
    'KON.03 - Akse': '01'
    'KON.10 - Konstruksjonsinndeling': Bru
    'KON.11 - Konstruksjonsdel': Peldetalj
    'KON.13 - Elementnavn': Detaljelement
    'KON.20 - Produksjonsenhet': PLD-1002
    'KON.30 - Plasseringsprioritet': 2 - Viker for 1
    'KON.31 - Plasseringsmerknad': Ikke angitt
    'KON.40 - Materialtype': Uspesifisert
    'KON.41 - Materialspesifikasjon': Uspesifisert
    'KON.51 - Produksjonsmerknad 1': Ikke angitt
    'KON.53 - Utførelsesmerknad 1': Ikke angitt

  KON_Betong:
    'BET.01 - Utførelsesklasse': '2'
    'BET.02 - Nøyaktighetsklasse': B
    'BET.04 - Materialspesifikasjon (dup)': B45 SV-Standard
    'BET.10 - Produksjonsmetode': Plasstøpt
    'BET.11 - Forskaling': Stående bord
    'BET.21 - Overdekning hovedarmering': 'UK, NS og FS: 75mm ±15mm, OK: 65mm ±15mm'
    'BET.30 - Diameter monteringsstenger': 12 mm
    'BET.31 - Overdekning monteringsstenger': 'UK, NS og FS: 60mm ±5mm, OK: 50mm ±5mm'

  KON_Stål:
    'STL.01 - Utførelsesklasse': EXC1
    'STL.02 - Tilvirkningstoleranse': '1'
    'STL.03 - Monteringstoleranse': '1'
    'STL.11 - Farge på siste dekkestrøk': RAL7036
    'STL.31 - Materialspesifikasjon (dup)': S355ML
    'STL.32 - Materialstandard': NS-EN 10025-4
    'STL.50 - Korrosjonsbeskyttelse': System 1 iht. SVV hb. N400 pkt. 9.2.1

  KON_Løsmasser:
    'LSM.01 - Materialspesifikasjon (dup)': Løsmasser
    'LSM.02 - Lagtykkelse': Ikke angitt
    'LSM.03 - Komprimering': Ikke angitt
    'LSM.04 - Løsmassemerknad krav': Ikke angitt

  KON_Peler:
    'PEL.01 - Pel-ID': Pel
    'PEL.02 - Belastningtype': Trykk
    'PEL.03 - Installert kapasitet [kN]': 0
    'PEL.05 - Helning [n/1]': 0
    'PEL.10 - Lengde ansett til teoretisk berg': 0 m
    'PEL.12 - Minimum innboring i godt berg/innramming i faste masser': 0 m
    'PEL.20 - Ansett-toleranse': 0 mm
    'PEL.21 - Retningstoleranse [%]': 0
    'PEL.22 - Helningstoleranse [%]': 0

rules:
  - id: loose-materials
    name_pattern: '^Løsmasser_[12]$'
    property_sets:
      - KON_Løsmasser
    exclude_property_sets:
      - KON_Felles
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Løsmasser

  - id: foundation
    name_pattern: '^Fundament$'
    property_sets:
      - KON_Betong
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Fundament
      KON_Felles:
        'KON.10 - Konstruksjonsinndeling': Underbygning
        'KON.11 - Konstruksjonsdel': Fundament
        'KON.13 - Elementnavn': Fundament
        'KON.40 - Materialtype': Betong
        'KON.41 - Materialspesifikasjon': B45 SV-Standard

  - id: pile-head
    name_pattern: '^Hode_Stålkjernepel$'
    property_sets:
      - KON_Peler
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Hode stålkjernepel
      KON_Felles:
        'KON.11 - Konstruksjonsdel': Stålkjernepel
        'KON.13 - Elementnavn': Hode stålkjernepel
        'KON.40 - Materialtype': Stål
        'KON.41 - Materialspesifikasjon': Ikke angitt
      KON_Peler:
        'PEL.01 - Pel-ID': Hode stålkjernepel

  - id: casing-pipe
    name_pattern: '^Foringsrør$'
    property_sets:
      - KON_Stål
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Foringsrør
      KON_Felles:
        'KON.11 - Konstruksjonsdel': Foringsrør
        'KON.13 - Elementnavn': Foringsrør
        'KON.40 - Materialtype': Stål
        'KON.41 - Materialspesifikasjon': S355ML

  - id: grout
    name_pattern: '^Omstøpningsmørtel$'
    property_sets:
      - KON_Felles
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Omstøpningsmørtel
      KON_Felles:
        'KON.11 - Konstruksjonsdel': Omstøpningsmørtel
        'KON.13 - Elementnavn': Omstøpningsmørtel
        'KON.40 - Materialtype': Mørtel
        'KON.41 - Materialspesifikasjon': Ikke angitt

  - id: steel-core-pile
    name_pattern: '^Stålkjernepel$'
    property_sets:
      - KON_Peler
    values:
      BIM_Tverrfaglig:
        'BIM.05 - Elementnavn': Stålkjernepel
      KON_Felles:
        'KON.11 - Konstruksjonsdel': Stålkjernepel
        'KON.13 - Elementnavn': Stålkjernepel
        'KON.40 - Materialtype': Stål
        'KON.41 - Materialspesifikasjon': Ikke angitt
      KON_Peler:
        'PEL.01 - Pel-ID': Stålkjernepel
